google:
  sheets:
    applicationName: dall
    tokenDirectoryPath: tokens
    credentialsFilePath: /credentials.json
    spreadsheetId: 15UKny9G821-Z6b5sVuz7A-VnNtQcrT68vaZQeV58fPk
    scopes:
      - https://www.googleapis.com/auth/spreadsheets

dall:
  city-centre-districts:
    - 1
    - 2
    - 3
    - 4
    - 6
    - 7
    - 8
  suburb-districts:
    - 9
    - 10
    - 12
    - 14
  links-range: Links!A1:A1000
  starting-cell-city-centre: 3
  starting-cell-suburb: 3
  ending-cell-city-centre: 103
  ending-cell-suburb: 103
  starting-column-city-centre: B
  starting-column-suburb: B
  ending-column-city-centre: L
  ending-column-suburb: L
  city-centre-sheet-name: Centre
  suburb-sheet-name: Banlieue

spring:
  main:
    web-application-type: NONE
